### ISSUE TITLE
mapMaker Add Row button doesn't work

### ISSUE THREAD

**Issue by ohiofi** [ohiofi/game-maps#21]
I was able to get the Add Column button to work, but the Add Row button doesn't seem to do anything?

**Comment by hmuhammadazeem** [comment]
Can you provide some elaboration? I might be able to help.

**Comment by not-arzuaga** [comment]
I will also look into this

**Comment by not-arzuaga** [comment]
@hmuhammadazeem  he is saying that when in mapmaker.html pressing add row doesnt do anything

**Comment by hmuhammadazeem** [comment]
@not-arzuaga Yea, got it. Thanks! :)

**Comment by not-arzuaga** [comment]
I think the issue is that when you create a new row, it doesnt append to the map so when ```let pixelElement = map[row][col]``` it breaks due to that

**Comment by not-arzuaga** [comment]
check #22

**Comment by not-arzuaga** [comment]
The other issue is to change the map accordingly, because if you make a change and then you do add column/row the map resets, but this allows to add rows

**Comment by hmuhammadazeem** [comment]
Hey @not-arzuaga, do you want to work on this? Or can I start trying this?

**Comment by not-arzuaga** [comment]
I fixed the adding of the row is working as the issue intended with #22 , the changing of the map accordingly should be another issue, I think. But I think I could fix work also on that

**Comment by ohiofi** [comment]
Thanks. I’ll close this issue then. I should’ve known that it was just an “index out of range” issue, but it was throwing a weird error message that confused me.
