### ISSUE TITLE
PNG video game sprites need background removed

### ISSUE THREAD

**Issue by ohiofi** [ohiofi/game-maps#9]
🎃H ⚰A 💀C 😰K 🍬T 🍫O 🕸B 👺E 😨R 👽F 🤡E 🎃S 👻T 😱! 🧟! 👹! 🕷! 😈! 🧛

I have some PNGs that I'd like to use as game sprites, but they need the background removed. These are from a Flash game that I made 10 years ago called [Phantom Of Power](http://ohiofi.com/phantomofpower/)

Here are the PNGs: [https://github.com/ohiofi/game-maps/tree/master/images/need_background_removed](https://github.com/ohiofi/game-maps/tree/master/images/need_background_removed
)

Use any photo editor you like. I've been using [Piskel](https://www.piskelapp.com). Just needs to be saved as a PNG with transparency when complete so that they will work in this HTML5 game. Thanks!

👻😱🧟👹🕷😈🧛🎃⚰💀😰🍬🍫🕸👺😨👽🤡🎃

**Comment by owenl131** [comment]
I would like to work on barrel1.png
